### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Added two great papers in the Maths Section. 

* [**The Matrix Calculus You Need For Deep Learning**](https://arxiv.org/abs/1802.01528)
* [**A Brief Introduction to Machine Learning for Engineers**](https://arxiv.org/abs/1709.02840)

### CODE REVIEW

**Comment by ayulockin** [comment]
Thank you for sharing.

**Comment by ayulockin** [comment]
Can you add the paper titled "A Brief Introduction to Machine Learning for Engineers" under the Miscellaneous section in the README?

**Comment by SauravMaheshkar** [comment]
Shifted "**A Brief Introduction to Machine Learning for Engineers**" to the Miscellaneous section in the README

**Comment by SauravMaheshkar** [comment]
I've also got some other great resources on Representation Learning. It's a great new area of research. I think that we should add links to those as well.

**Comment by ayulockin** [comment]
Yes, that's true. Will you be down to make a new PR with the resources. Add a new section name `Unsupervised Representation Learning`.

**Comment by SauravMaheshkar** [comment]
Ok. I'll make a new PR and add some papers and resources on Unsupervised Representation Learning

**Pull request merged**
